# Generated by Django 3.2.4 on 2021-06-20 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topGameUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.BigIntegerField()),
                ('date_of_assignment', models.DateTimeField(default=django.utils.timezone.now)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
